import {
  Issuer,
  CredentialType,
  Credential,
  CompositionRule,
  GovernanceApplication,
  GovernanceAction,
  ClaimableCredential,
  BatchIssueJob,
} from "@/lib/types";

const NOW = Math.floor(Date.now() / 1000);
const DAY = 86400;

// ─── Issuers ─────────────────────────────────

export const MOCK_ISSUERS: Issuer[] = [
  {
    address: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    name: "Massachusetts Institute of Technology",
    type: "university",
    registeredAt: NOW - 90 * DAY,
    status: "active",
    description: "Department of Computer Science at MIT",
    website: "https://web3.mit.edu",
    email: "web3@mit.edu",
    logoUrl: "",
    credibilityScore: 95,
    totalIssued: 156,
    totalRevoked: 3,
  },
  {
    address: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    name: "XYZ Training Institute",
    type: "training_org",
    registeredAt: NOW - 60 * DAY,
    status: "active",
    description: "Professional training and certification organization",
    website: "https://xyztraining.org",
    email: "admin@xyztraining.org",
    logoUrl: "",
    credibilityScore: 88,
    totalIssued: 89,
    totalRevoked: 1,
  },
  {
    address: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    name: "MIT Web3 Club",
    type: "club",
    registeredAt: NOW - 45 * DAY,
    status: "active",
    description: "Official coding club of MIT",
    website: "https://codingclub.abcuniversity.edu",
    email: "codingclub@abcuniversity.edu",
    logoUrl: "",
    credibilityScore: 82,
    totalIssued: 42,
    totalRevoked: 0,
  },
];

// ─── Credential Types ────────────────────────

export const MOCK_CREDENTIAL_TYPES: CredentialType[] = [
  {
    id: "CT-001",
    name: "Web3 Foundations",
    description:
      "Core concepts of blockchain technology, cryptography, and decentralized networks",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: true,
    createdAt: NOW - 80 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0, // never expires
  },
  {
    id: "CT-002",
    name: "Smart Contract Security",
    description:
      "Advanced vulnerability analysis and secure coding practices for smart contracts",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: true,
    createdAt: NOW - 75 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
  {
    id: "CT-003",
    name: "DeFi Protocols",
    description:
      "Architecture and mechanics of decentralized finance applications",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: true,
    createdAt: NOW - 70 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
  {
    id: "CT-004",
    name: "Zero-Knowledge Proofs",
    description:
      "Implementation of zero-knowledge proofs and privacy-preserving protocols",
    category: "technical",
    tier: "advanced",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: true,
    createdAt: NOW - 65 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
  {
    id: "CT-005",
    name: "Cloud Deployment Workshop",
    description:
      "Hands-on workshop covering cloud deployment with AWS, Docker, and CI/CD pipelines",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    issuerName: "XYZ Training Institute",
    evidenceRequired: false,
    createdAt: NOW - 55 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 31536000, // 1 year expiry
  },
  {
    id: "CT-006",
    name: "Hackathon Winner — Spring 2025",
    description:
      "First place winner at the MIT Spring 2025 Hackathon",
    category: "achievement",
    tier: "advanced",
    issuerAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    issuerName: "MIT Web3 Club",
    evidenceRequired: true,
    createdAt: NOW - 30 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
  {
    id: "CT-007",
    name: "Machine Learning Basics",
    description:
      "Introduction to machine learning concepts, supervised and unsupervised learning",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: true,
    createdAt: NOW - 50 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
  {
    id: "CT-008",
    name: "AWS Solutions Architect Prep",
    description:
      "Preparation course for AWS Solutions Architect Associate certification exam",
    category: "certification",
    tier: "intermediate",
    issuerAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    issuerName: "XYZ Training Institute",
    evidenceRequired: true,
    createdAt: NOW - 40 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 15552000, // 6 months expiry
  },
  {
    id: "CT-009",
    name: "Technical Communication",
    description:
      "Effective technical writing, documentation, and presentation skills",
    category: "soft_skill",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: false,
    createdAt: NOW - 35 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
  {
    id: "CT-010",
    name: "Blockchain Developer Mastery",
    description:
      "Composite credential demonstrating mastery across Web3, Smart Contracts, DeFi, and ZK Proofs",
    category: "certification",
    tier: "expert",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    evidenceRequired: false,
    createdAt: NOW - 60 * DAY,
    status: "active",
    badgeImageUrl: "",
    expiryDuration: 0,
  },
];

// ─── Credentials ─────────────────────────────

export const MOCK_CREDENTIALS: Credential[] = [
  {
    id: "CRED-00001",
    asaId: 100001,
    credentialTypeId: "CT-001",
    credentialTypeName: "Web3 Foundations",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
    issuedAt: NOW - 40 * DAY,
    status: "active",
    txId: "TX001ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 40 * DAY,
    privacyLevel: "public",
  },
  {
    id: "CRED-00002",
    asaId: 100002,
    credentialTypeId: "CT-002",
    credentialTypeName: "Smart Contract Security",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
    issuedAt: NOW - 35 * DAY,
    status: "active",
    txId: "TX002ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 35 * DAY,
    privacyLevel: "public",
  },
  {
    id: "CRED-00003",
    asaId: 100003,
    credentialTypeId: "CT-003",
    credentialTypeName: "DeFi Protocols",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
    issuedAt: NOW - 25 * DAY,
    status: "active",
    txId: "TX003ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 25 * DAY,
    privacyLevel: "public",
  },
  {
    id: "CRED-00004",
    asaId: 100004,
    credentialTypeId: "CT-004",
    credentialTypeName: "Zero-Knowledge Proofs",
    category: "technical",
    tier: "advanced",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3",
    issuedAt: NOW - 15 * DAY,
    status: "active",
    txId: "TX004ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 15 * DAY,
    privacyLevel: "public",
  },
  {
    id: "CRED-00005",
    asaId: 100005,
    credentialTypeId: "CT-006",
    credentialTypeName: "Hackathon Winner — Spring 2025",
    category: "achievement",
    tier: "advanced",
    issuerAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    issuerName: "MIT Web3 Club",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4",
    issuedAt: NOW - 10 * DAY,
    status: "active",
    txId: "TX005ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 10 * DAY,
    privacyLevel: "public",
  },
  {
    id: "CRED-00006",
    asaId: 100006,
    credentialTypeId: "CT-007",
    credentialTypeName: "Machine Learning Basics",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5",
    issuedAt: NOW - 45 * DAY,
    status: "revoked",
    revokedAt: NOW - 20 * DAY,
    revocationReason: "Course requirements not met upon review",
    txId: "TX006ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 45 * DAY,
    privacyLevel: "public",
  },
  // ─── Expiring credential for demo ──────────
  {
    id: "CRED-00007",
    asaId: 100007,
    credentialTypeId: "CT-008",
    credentialTypeName: "AWS Solutions Architect Prep",
    category: "certification",
    tier: "intermediate",
    issuerAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    issuerName: "XYZ Training Institute",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6",
    issuedAt: NOW - 150 * DAY,
    status: "active",
    txId: "TX007ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    expiresAt: NOW + 20 * DAY, // expires in 20 days — "expiring soon"
    claimStatus: "claimed",
    claimedAt: NOW - 150 * DAY,
    privacyLevel: "public",
  },
  // ─── Claimable credential (in escrow) ──────
  {
    id: "CRED-00008",
    asaId: 100008,
    credentialTypeId: "CT-009",
    credentialTypeName: "Technical Communication",
    category: "soft_skill",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    issuedAt: NOW - 2 * DAY,
    status: "pending",
    txId: "TX008ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimable",
    privacyLevel: "public",
  },
  // ─── Credential for student2 ───────────────
  {
    id: "CRED-00009",
    asaId: 100009,
    credentialTypeId: "CT-001",
    credentialTypeName: "Web3 Foundations",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "Massachusetts Institute of Technology",
    recipientAddress: "STUDENT2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ234568",
    evidenceHash: "sha256:z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4j3i2h1g0",
    issuedAt: NOW - 20 * DAY,
    status: "active",
    txId: "TX009ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    claimStatus: "claimed",
    claimedAt: NOW - 20 * DAY,
    privacyLevel: "public",
  },
];

// ─── Composition Rules ───────────────────────

export const MOCK_COMPOSITION_RULES: CompositionRule[] = [
  {
    id: "COMP-001",
    name: "Blockchain Developer Mastery",
    description:
      "Demonstrates mastery across Web3, Smart Contracts, DeFi, and ZK Proofs",
    definedBy: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    definedByName: "Massachusetts Institute of Technology",
    requiredCredentialTypeIds: [
      "CT-001",
      "CT-002",
      "CT-003",
      "CT-004",
      "CT-005",
    ],
    requiredCredentialTypes: [], // populated below
    compositionType: "all_required",
    compositeCredentialTypeId: "CT-010",
    autoIssue: true,
    createdAt: NOW - 60 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
];

// Populate required credential types
MOCK_COMPOSITION_RULES[0].requiredCredentialTypes =
  MOCK_CREDENTIAL_TYPES.filter((t) =>
    MOCK_COMPOSITION_RULES[0].requiredCredentialTypeIds.includes(t.id)
  );

// ─── Governance Applications ─────────────────

export const MOCK_GOVERNANCE_APPLICATIONS: GovernanceApplication[] = [
  {
    id: "APP-001",
    applicantAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    institutionName: "Massachusetts Institute of Technology",
    institutionType: "department",
    email: "web3@mit.edu",
    website: "https://web3.mit.edu",
    description:
      "Department of Computer Science at MIT. Offering undergraduate and graduate programs in CS since 1985.",
    status: "approved",
    submittedAt: NOW - 95 * DAY,
    reviewedAt: NOW - 90 * DAY,
    reviewedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reviewNote: "Verified institution. Domain match confirmed.",
    txId: "TXGOV001ABCDEFGHIJKLMNOPQRSTUV",
  },
  {
    id: "APP-002",
    applicantAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    institutionName: "XYZ Training Institute",
    institutionType: "training_org",
    email: "admin@xyztraining.org",
    website: "https://xyztraining.org",
    description:
      "Professional training and certification organization specializing in cloud computing and DevOps.",
    status: "approved",
    submittedAt: NOW - 65 * DAY,
    reviewedAt: NOW - 60 * DAY,
    reviewedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reviewNote: "Training organization verified via partnership documents.",
    txId: "TXGOV002ABCDEFGHIJKLMNOPQRSTUV",
  },
  {
    id: "APP-003",
    applicantAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    institutionName: "MIT Web3 Club",
    institutionType: "club",
    email: "codingclub@abcuniversity.edu",
    website: "https://codingclub.abcuniversity.edu",
    description: "Official coding club of MIT.",
    status: "approved",
    submittedAt: NOW - 50 * DAY,
    reviewedAt: NOW - 45 * DAY,
    reviewedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reviewNote: "Club verified under MIT umbrella.",
    txId: "TXGOV003ABCDEFGHIJKLMNOPQRSTUV",
  },
  // ─── Pending application for demo ──────────
  {
    id: "APP-004",
    applicantAddress: "PENDING1INSTITUTEXYZABCDEFGHIJKLMNOPQRSTUV",
    institutionName: "Global Tech Academy",
    institutionType: "training_org",
    email: "admin@globaltechacademy.io",
    website: "https://globaltechacademy.io",
    description:
      "Online technology academy offering courses in blockchain development, cybersecurity, and data science.",
    documentUri: "ipfs://QmPendingDoc123456789",
    documentHash: "sha256:pending1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f",
    status: "pending",
    submittedAt: NOW - 3 * DAY,
  },
  // ─── Under review application ──────────────
  {
    id: "APP-005",
    applicantAddress: "REVIEW1UNIVERSITYABCDEFGHIJKLMNOPQRSTUVWXY",
    institutionName: "Metro State University — Engineering",
    institutionType: "department",
    email: "engineering@metrostate.edu",
    website: "https://engineering.metrostate.edu",
    description:
      "Department of Engineering at Metro State University. ABET accredited programs in mechanical, civil, and software engineering.",
    documentUri: "ipfs://QmReviewDoc987654321",
    documentHash: "sha256:review1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f",
    status: "under_review",
    submittedAt: NOW - 7 * DAY,
    reviewedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reviewNote: "Reviewing ABET accreditation documents.",
  },
  // ─── Rejected application ──────────────────
  {
    id: "APP-006",
    applicantAddress: "REJECT1FAKECERTXYZABCDEFGHIJKLMNOPQRSTUVW",
    institutionName: "QuickCerts Online",
    institutionType: "company",
    email: "info@quickcerts.xyz",
    website: "https://quickcerts.xyz",
    description: "Fast online certification provider.",
    status: "rejected",
    submittedAt: NOW - 14 * DAY,
    reviewedAt: NOW - 10 * DAY,
    reviewedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reviewNote:
      "Unable to verify institution legitimacy. No accreditation documents provided. Website domain registered 2 weeks ago.",
    txId: "TXGOV006ABCDEFGHIJKLMNOPQRSTUV",
  },
];

// ─── Governance Actions (Audit Trail) ────────

export const MOCK_GOVERNANCE_ACTIONS: GovernanceAction[] = [
  {
    id: "ACTION-001",
    type: "application_submitted",
    targetAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    targetName: "Massachusetts Institute of Technology",
    performedBy: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    reason: "Initial issuer registration application",
    timestamp: NOW - 95 * DAY,
    applicationId: "APP-001",
  },
  {
    id: "ACTION-002",
    type: "issuer_approved",
    targetAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    targetName: "Massachusetts Institute of Technology",
    performedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reason: "Verified institution. Domain match confirmed.",
    timestamp: NOW - 90 * DAY,
    txId: "TXGOV001ABCDEFGHIJKLMNOPQRSTUV",
    applicationId: "APP-001",
  },
  {
    id: "ACTION-003",
    type: "application_submitted",
    targetAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    targetName: "XYZ Training Institute",
    performedBy: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    reason: "Initial issuer registration application",
    timestamp: NOW - 65 * DAY,
    applicationId: "APP-002",
  },
  {
    id: "ACTION-004",
    type: "issuer_approved",
    targetAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    targetName: "XYZ Training Institute",
    performedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reason: "Training organization verified via partnership documents.",
    timestamp: NOW - 60 * DAY,
    txId: "TXGOV002ABCDEFGHIJKLMNOPQRSTUV",
    applicationId: "APP-002",
  },
  {
    id: "ACTION-005",
    type: "application_submitted",
    targetAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    targetName: "MIT Web3 Club",
    performedBy: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    reason: "Initial issuer registration application",
    timestamp: NOW - 50 * DAY,
    applicationId: "APP-003",
  },
  {
    id: "ACTION-006",
    type: "issuer_approved",
    targetAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    targetName: "MIT Web3 Club",
    performedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reason: "Club verified under MIT umbrella.",
    timestamp: NOW - 45 * DAY,
    txId: "TXGOV003ABCDEFGHIJKLMNOPQRSTUV",
    applicationId: "APP-003",
  },
  {
    id: "ACTION-007",
    type: "application_submitted",
    targetAddress: "PENDING1INSTITUTEXYZABCDEFGHIJKLMNOPQRSTUV",
    targetName: "Global Tech Academy",
    performedBy: "PENDING1INSTITUTEXYZABCDEFGHIJKLMNOPQRSTUV",
    reason: "Initial issuer registration application",
    timestamp: NOW - 3 * DAY,
    applicationId: "APP-004",
  },
  {
    id: "ACTION-008",
    type: "application_reviewed",
    targetAddress: "REVIEW1UNIVERSITYABCDEFGHIJKLMNOPQRSTUVWXY",
    targetName: "Metro State University — Engineering",
    performedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reason: "Reviewing ABET accreditation documents.",
    timestamp: NOW - 5 * DAY,
    applicationId: "APP-005",
  },
  {
    id: "ACTION-009",
    type: "issuer_rejected",
    targetAddress: "REJECT1FAKECERTXYZABCDEFGHIJKLMNOPQRSTUVW",
    targetName: "QuickCerts Online",
    performedBy: "ADMIN1CREDGRAPHGOVERNANCEWALLETXYZ234567890",
    reason:
      "Unable to verify institution legitimacy. No accreditation documents provided.",
    timestamp: NOW - 10 * DAY,
    txId: "TXGOV006ABCDEFGHIJKLMNOPQRSTUV",
    applicationId: "APP-006",
  },
];
