import {
  Issuer,
  CredentialType,
  Credential,
  CompositionRule,
} from "@/lib/types";

const NOW = Math.floor(Date.now() / 1000);
const DAY = 86400;

export const MOCK_ISSUERS: Issuer[] = [
  {
    address: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    name: "ABC University — Computer Science",
    type: "department",
    registeredAt: NOW - 90 * DAY,
    status: "active",
    description: "Department of Computer Science at ABC University",
    website: "https://cs.abcuniversity.edu",
    logoUrl: "",
  },
  {
    address: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    name: "XYZ Training Institute",
    type: "training_org",
    registeredAt: NOW - 60 * DAY,
    status: "active",
    description: "Professional training and certification organization",
    website: "https://xyztraining.org",
    logoUrl: "",
  },
  {
    address: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    name: "ABC University — Coding Club",
    type: "club",
    registeredAt: NOW - 45 * DAY,
    status: "active",
    description: "Official coding club of ABC University",
    website: "https://codingclub.abcuniversity.edu",
    logoUrl: "",
  },
];

export const MOCK_CREDENTIAL_TYPES: CredentialType[] = [
  {
    id: "CT-001",
    name: "React.js Proficiency",
    description: "Demonstrated proficiency in React.js framework including hooks, state management, and component architecture",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    evidenceRequired: true,
    createdAt: NOW - 80 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-002",
    name: "Database Fundamentals",
    description: "Core knowledge of relational databases, SQL, normalization, and query optimization",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    evidenceRequired: true,
    createdAt: NOW - 75 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-003",
    name: "Node.js Backend Development",
    description: "Proficiency in server-side development with Node.js, Express, and RESTful APIs",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    evidenceRequired: true,
    createdAt: NOW - 70 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-004",
    name: "API Design Mastery",
    description: "Advanced API design patterns, versioning, authentication, and documentation",
    category: "technical",
    tier: "advanced",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    evidenceRequired: true,
    createdAt: NOW - 65 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-005",
    name: "Cloud Deployment Workshop",
    description: "Hands-on workshop covering cloud deployment with AWS, Docker, and CI/CD pipelines",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER2XYZABCDEFGHIJKLMNOPQRSTUVWXYZ2345678",
    issuerName: "XYZ Training Institute",
    evidenceRequired: false,
    createdAt: NOW - 55 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-006",
    name: "Hackathon Winner — Spring 2025",
    description: "First place winner at the ABC University Spring 2025 Hackathon",
    category: "achievement",
    tier: "advanced",
    issuerAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    issuerName: "ABC University — Coding Club",
    evidenceRequired: true,
    createdAt: NOW - 30 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-007",
    name: "Machine Learning Basics",
    description: "Introduction to machine learning concepts, supervised and unsupervised learning",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    evidenceRequired: true,
    createdAt: NOW - 50 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
  {
    id: "CT-010",
    name: "Full Stack Developer",
    description: "Composite credential demonstrating mastery across frontend, backend, databases, API design, and cloud deployment",
    category: "certification",
    tier: "expert",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    evidenceRequired: false,
    createdAt: NOW - 60 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
];

export const MOCK_CREDENTIALS: Credential[] = [
  {
    id: "CRED-00001",
    asaId: 100001,
    credentialTypeId: "CT-001",
    credentialTypeName: "React.js Proficiency",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
    issuedAt: NOW - 40 * DAY,
    status: "active",
    txId: "TX001ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
  {
    id: "CRED-00002",
    asaId: 100002,
    credentialTypeId: "CT-002",
    credentialTypeName: "Database Fundamentals",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
    issuedAt: NOW - 35 * DAY,
    status: "active",
    txId: "TX002ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
  {
    id: "CRED-00003",
    asaId: 100003,
    credentialTypeId: "CT-003",
    credentialTypeName: "Node.js Backend Development",
    category: "technical",
    tier: "intermediate",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
    issuedAt: NOW - 25 * DAY,
    status: "active",
    txId: "TX003ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
  {
    id: "CRED-00004",
    asaId: 100004,
    credentialTypeId: "CT-004",
    credentialTypeName: "API Design Mastery",
    category: "technical",
    tier: "advanced",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3",
    issuedAt: NOW - 15 * DAY,
    status: "active",
    txId: "TX004ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
  {
    id: "CRED-00005",
    asaId: 100005,
    credentialTypeId: "CT-006",
    credentialTypeName: "Hackathon Winner — Spring 2025",
    category: "achievement",
    tier: "advanced",
    issuerAddress: "ISSUER3HACKCLUBDEFGHIJKLMNOPQRSTUVWXYZ23456",
    issuerName: "ABC University — Coding Club",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4",
    issuedAt: NOW - 10 * DAY,
    status: "active",
    txId: "TX005ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
  {
    id: "CRED-00006",
    asaId: 100006,
    credentialTypeId: "CT-007",
    credentialTypeName: "Machine Learning Basics",
    category: "technical",
    tier: "beginner",
    issuerAddress: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    issuerName: "ABC University — Computer Science",
    recipientAddress: "STUDENT1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890",
    evidenceHash: "sha256:f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5",
    issuedAt: NOW - 45 * DAY,
    status: "revoked",
    revokedAt: NOW - 20 * DAY,
    revocationReason: "Course requirements not met upon review",
    txId: "TX006ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
];

export const MOCK_COMPOSITION_RULES: CompositionRule[] = [
  {
    id: "COMP-001",
    name: "Full Stack Developer",
    description: "Demonstrates mastery across frontend, backend, databases, API design, and cloud deployment",
    definedBy: "ISSUER1ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABC",
    definedByName: "ABC University — Computer Science",
    requiredCredentialTypeIds: ["CT-001", "CT-002", "CT-003", "CT-004", "CT-005"],
    requiredCredentialTypes: MOCK_CREDENTIAL_TYPES.filter((t) =>
      ["CT-001", "CT-002", "CT-003", "CT-004", "CT-005"].includes(t.id)
    ),
    compositionType: "all_required",
    compositeCredentialTypeId: "CT-010",
    autoIssue: true,
    createdAt: NOW - 60 * DAY,
    status: "active",
    badgeImageUrl: "",
  },
];
